### ISSUE TITLE
Can the font size be a little bigger?

### ISSUE THREAD

**Issue by disturbio** [kentonv/etherpad-lite#24]
Hi!

One of the issues we have been dealing with etherpad in sandstorm is that the font size cannot be made bigger with the usual ctrl + because everything grows and not just the pad buttons. Currently there is no plugin to configure the font size, and i just use to edit manually the etherpad css to fix this (there is one to configure text family, font size, etc but if you write something new it's back to the old size).

https://github.com/ether/etherpad-lite/issues/2671

If it's not possible, what would be the options to get this done? there are a couple of coworkers complaining they will get blind ;)

**Comment by kentonv** [comment]
Indeed, this is something we plan to do soon as part of a general Etherpad facelift. The tiny font annoys me too! :)

**Comment by disturbio** [comment]
That's great. Trying to find out how to help i found this plugin that can maybe help with that https://github.com/JohnMcLear/ep_user_font_size

Thank you!

**Comment by creatinglake** [comment]
Also, as it is you can't select a larger font size than 20. Ideally you could type in your desired font size too.

**Comment by kentonv** [comment]
Release 1.6.0~2016-11-15 increases font size from 12px to 15px. You should get an update notification with 24 hours.
