### ISSUE TITLE
Comment threads don't get updated correctly

### ISSUE THREAD

**Issue by zarvox** [kentonv/etherpad-lite#26]
To reproduce:
- User A opens a grain in browser tab 1.
- User A leaves a comment.
- User A keeps browser tab 1 open.
- User B replies to the comment.

I would expect that when user A hovers over their comment, they should see their comment and user B's reply.

Instead, they see just their own comment.

---

Additionally, if user B makes a comment elsewhere in the pad, user A will see that range highlighted, but when user A hovers over that range, they see the first thread, rather than the new comment.

**Comment by kentonv** [comment]
> I would expect that when user A hovers over their comment, they should see their comment and user B's reply.

This is fixed by: https://github.com/kentonv/ep_comments/commit/c8f6ce84aa65a51b24c7aab73e6261ef8e5b57cd

> Additionally, if user B makes a comment elsewhere in the pad, user A will see that range highlighted, but when user A hovers over that range, they see the first thread, rather than the new comment.

I'm unable to reproduce this, although I think I have observed it in the past. Can you provide more specific reproduction steps, starting from creating the pad?

**Comment by zarvox** [comment]
I tried for a bit to get the second bug to reproduce, but I also couldn't make it happen again.  I wouldn't be surprised if the fix you made also happens to fix the second symptom, so I'll close this issue and open a new one if I encounter the odd behavior again.
