### ISSUE TITLE
Comments at end of long document are very hard to interact with

### ISSUE THREAD

**Issue by zarvox** [kentonv/etherpad-lite#27]
When a comment is made on a range of text toward the end of a pad with scroll height larger than the window height, it's basically impossible to read/interact with the comment thread, because the comment box always goes below the highlighted section, so in this case it extends the length of the document offscreen. But if you scroll down to try to read the comment, you likely stop hovering over the highlighted section, and the comment thread disappears, which causes the height to return to its previous value. It becomes very hard to actually read comments.

Possible solutions, in order of most desirable to least desirable, include:
- make clicking on a region with comments toggle showing the comment thread, so that you don't have to be very precise with a mouse ever
- don't immediately hide the comment thread when hover ends, and keep the comment thread visible if hovering over the comment thread box
- show the comment box somewhere else that doesn't affect scroll height (some threads may be longer than the document, though)

**Comment by kentonv** [comment]
Fixed in 1.6.0~2016-11-15. You should get an update notification with 24 hours.
