### ISSUE TITLE
Twitchy comment boxes under certain layouts

### ISSUE THREAD

**Issue by zarvox** [kentonv/etherpad-lite#30]
When hovering over a commented-on range, Etherpad shows a popup box with the comment.  Under certain circumstances, this will appear directly under the mouse, which means the mouse is no longer hovering over the commented range, so Etherpad hides the popup box.  But then the mouse is hovering over a commented-on range again, so Etherpad shows the box.

This makes it very hard to actually read the comment thread.  An example of a problematic layout for a comment can be found in the screenshots below.  The following two frames alternate as quickly as the browser can render them:

![frame1](https://cloud.githubusercontent.com/assets/307325/18485799/327ea734-79a3-11e6-8e4d-0ae211b50b1c.png)

![frame2](https://cloud.githubusercontent.com/assets/307325/18485811/44d8da6c-79a3-11e6-8f18-c82a988f93b7.png)

**Comment by kentonv** [comment]
Fixed in 1.6.0~2016-11-15. You should get an update notification with 24 hours.
