### ISSUE TITLE
Missing authorship information

### ISSUE THREAD

**Issue by zarvox** [kentonv/etherpad-lite#31]
Reproduction:
- User 1 creates new etherpad grain
- User 1 creates new sharing link via share access button
- User 2 (who is already logged in) opens that link
- User 1 types into the window
- User 2 sees that text attributed to "Unknown Author".  I would expect it to show User 1's display name.
- User 2 types into the window
- User 1 sees that text attributed to "Unknown Author".  I would expect it to show User 2's display name.

If User 1 refreshes the page, the apparent authorship information is corrected for both users.  (I didn't test what happens if User 2 does likewise; I imagine it would probably also fix the attribution labels.)

In the screenshots below, Alice Dev Admin is User 1 and Dave Dev User is User 2.

![alice](https://cloud.githubusercontent.com/assets/307325/18486234/34a120e4-79a5-11e6-8e90-f2bb5f8af6d9.png)

![dave](https://cloud.githubusercontent.com/assets/307325/18486239/3e2f34d4-79a5-11e6-974e-35a004ce342e.png)

**Comment by zarvox** [comment]
This bug came up in user testing again this week.

**Comment by zarvox** [comment]
This came up in user testing once again last week.

**Comment by kentonv** [comment]
Fixed in 1.6.0~2016-11-15. You should get an update notification with 24 hours.
