### ISSUE TITLE
Include comment text in body of app activity events

### ISSUE THREAD

**Issue by zarvox** [kentonv/etherpad-lite#32]
Right now, the activity event includes the path, thread path, and title, but no body.

If it included the comment, we could include the body of the comment in email notifications.

**Comment by kentonv** [comment]
Fixed by:

https://github.com/kentonv/etherpad-lite/commit/e5d9b193f3fd447a7c9b668ddbbe0119ac98570a
https://github.com/kentonv/ep_comments/commit/5f67d77109a1ef748a4260d70010be05130b4efb
