### ISSUE TITLE
Minor design quibble: Clicking in the comments box results in its background color changing

### ISSUE THREAD

**Issue by paulproteus** [kentonv/etherpad-lite#33]
Steps to reproduce:

- Create a new Etherpad document with today's release of Etherpad

- Leave a comment

- Click on any background (non-text) area of the comments box

Expected results:

- nothing

Actual results:

- Comments box, about 0.2 seconds later, has its background blink

Image attached. Ignore the black rectangle where the mouse should be.

![out](https://cloud.githubusercontent.com/assets/25457/20327645/f76c0fac-ab5b-11e6-967e-c8c781c99de9.gif)

**Comment by paulproteus** [comment]
When you see the black rectangles appear, that's when I click the mouse, fwiw.

**Comment by kentonv** [comment]
Apparently you can close a bug on one repo with a commit to another repo. Neat.

Anyway, version 2016-11-16 fixes this and also (much more importantly) eliminates keystroke lag.
